secretGenerator:
- name: mysql-pass
  literals:
  - password=YOUR_PASSWORD
resources:
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
  - phpadmin-deployment.yaml
  - phpdatabase-deployment.yaml
