apiVersion: v1
kind: Service
metadata:
  name: phpdatabase
  labels:
    app: phpdatabase
spec:
  ports:
    - port: 8000
  selector:
    app: phpdatabase
    tier: frontend
  type: LoadBalancer

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: phpdatabase
  labels:
    app: phpdatabase
spec:
  selector:
    matchLabels:
      app: phpdatabase
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpdatabase
        tier: frontend
    spec:
      containers:
      - image: mprambadi/php-docker:1.0
        name: phpdatabase
        env:
        - name: DB_HOST
          value: wordpress-mysql
        - name: DB_USERNAME
          value: root
        - name: DB_NAME
          value: phpapp
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 8000
          name: phpdatabase